# Generated by Django 4.1.6 on 2023-02-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('location', models.CharField(default='', max_length=40)),
                ('owner_id', models.CharField(max_length=10)),
            ],
        ),
    ]
